+ du oneliner, x some bs, move stuff around

diff --git a/cmds b/cmds
--- a/cmds
+++ b/cmds
@@ -5,7 +5,7 @@
 
 $ sudo mount /dev/sdxy /run/myflashhh
 $ sudo mount -t ntfs-3g /dev/sdxy /run/dribe
-$ cat /sys/block/---/queue/rotational           // 1: hdd; 0: ssd
+$ cat /sys/block/---/queue/rotational             // 1: hdd; 0: ssd
 
 
 #################
@@ -17,11 +17,13 @@ $ mkdir -p ~/.config/{bspwm,sxhkd}                // -p make parent dirs as need
 
 $ mkdir -p dir2/folders{1,2}                      // create subirs folders1 and folders2
 
+
 ################
 ###   VIM    ###
 ################
 
 :w !sudo tee %					  // writes file w/elevated privileges. It asks for as terminal, can't do it
+
 
 ################
 ###   COPY   ###
@@ -31,7 +33,7 @@ $ cp -rv /source/ /to/destiny                      // copy folder
                                                    // -v verbose
                                                    // -r recursive
 
-$ rsync -vahz --dry-run /source                     // list files to copy
+$ rsync -vahz --dry-run /source                    // list files to copy
 
 $ rsync -vahzP /source/ /to/destiny/               // -v verbose
                                                    // -a archive (equals to -rlptogD)
@@ -68,7 +70,6 @@ $ shred -vufzn 4                                 // -v verbose
 ## Use the find command to execute shred -uvz recursively:
 $ find path/to/dir/ -type f -exec shred -vufzn 3 {} \; // shred directory recursively
 
-
 find path/to/dir/ -type f -print0 | xargs -0 -I {} sh -c 'printf "\033[3$((RANDOM%6+1))m"; shred -vufzn 3 "$1"; printf "\033[0m"' sh {}
 
 
@@ -84,7 +85,7 @@ $ tar -xvzf document.tar.gz                       //  x: extract files
                                                   //	z: decompress files
                                                   //	f: filename to work on
 
-$ tar -tzf document.tar.gz		             // list contents of .tar file before extracting
+$ tar -tzf document.tar.gz		                   // list contents of .tar file before extracting
 
 $ 7za -y x '*.zip'                               // -y: assumes yes to all queries
                                                  //  x: extract files with full paths
@@ -108,15 +109,12 @@ $ fg							       // go back to htop
 ###   HARDWARE   ###
 ####################
 
-$ inxi -Fx						        // complete fastfetchish
+$ inxi -Fx						                   // complete fastfetchish
 
-## NETWORK
-# test-ipv6.com
+$ inxi -Na					                     // -N network devices, driver
+                                         // -a advanced sys admin data
 
-$ inxi -Na					            // -N network devices, driver
-                                        // -a advanced sys admin data
-
-$ mhwd						            // display & network controllers
+$ mhwd						                       // display & network controllers
 
 ## BATTERY
 $ upower -i /org/freedesktop/UPower/devices/battery_BAT0 
@@ -145,18 +143,18 @@ $ nmcli device wifi connect <SSID_or_BSSID> password <password>
 $ nmcli connection                               // list connection historial
 $ lspci | grep -i net                            // list network controllers
 $ python3 -m http.server 8000                    // takes dir's content and serves it at localhost:8000
-reflector --latest 50 --number 20 --sort score --save ...
-#still have to try next one:
-$ mtr archlinux.org                              // investigate net connex; mixes funcx of ping and traceroute
 
-$ curl -F "file=@filename.foo" 0x0.st           // cloud
+#still have to try next one:
+$ mtr archlinux.org                              // investigate net connex; mixes funx of ping and traceroute
+
+$ curl -F "file=@filename.foo" 0x0.st            // cloud storage
 
 
 ##################
 ###   KERNEL   ###
 ##################
 
-$ uname -srm					 // -s --kernel-name
+$ uname -srm				                          	 // -s --kernel-name
                                                  // -r --kernel-release
                                                  // -m --machine (hardware name)
 
@@ -165,18 +163,110 @@ $ pacman -Q | grep linux                         // list kernels related softwar
 $ sudo pacman -S linux                           // install latest stable kernel
 
 
-
 ###################
 ###   PACMAN    ###
 ###################
 
 $ sudo pacman -Syu --ignore=vlc                 // ignore vlc temporarily
 $ sudo pacman -Syyu --overwrite "*"             // when 'exists in filesystem' while update
-$ pamac clean --keep 1				// clean cache, keeps latest version pkg ver
+$ pamac clean --keep 1		                  		// clean cache, keeps latest version pkg ver
 $ pacman -Fy                                    // -F query files db, look for pkg owning certain file, etc
                                                 // -y refreshes pkg file db from server. 
 $ pacman -F pactl                               // shows list of pkgs related to pactl
 
+
+
+$ nohup <SOMEPKG> &                                    // start from/indie of terminal
+
+$ xdg-open file.txt				                           	// open file
+$ xdg-mime query filetype file.pdf	              		// get filetype
+$ xdg-mime query default application/pdf	          	// ask default pdf app 
+$ xdg-mime default some_app.desktop application/pdf 	// set some_app as default pdf
+                                                      // if .desktop doesnt exist, create in /usr/share/applications/
+
+$ /bin/ls					                                  	// outputs original ls w/o aliases
+$ /bin/ls | entr -s 'firefox localhost:3000'
+
+$ cd -						                                  	// into last dir
+
+$ ^r						                                    	// search cmd mode
+                                                      // ^R again, search next one
+
+$ history						// show cmds history
+## add to bashrc (have to try on zshrc):
+## HISTTIMEFORMAT="%Y-%m-%d %T "	
+
+$ cmd1 && cmd2                                  // runs cmd2 only after cmd1
+$ cmd1; cmd2                                    // runs cmd2 even if cmd1 fails
+
+$ git commit -m "whatever..." || echo "Commit failed" // conditional execution
+
+$ grep 'string' directory-path/*.*              // find 'string' in all files of
+                                                // directory-path/
+
+$ pstree                                        // show processes currently running on system
+
+$ sudo loadkeys -d                              // change keyboard layout to default
+
+$ cat error.log | sort | uniq                   // cat to read file 
+                                                // sort it line by line 
+                                                // uniq to eliminate duplicates
+
+$ chown -R xxx: xxx                             // change ownership, after recylcing home dir for instance
+
+echo $(find . -maxdepth 2 -type d) >> ALBUMS
+## edit /etc/makepkg.conf around line 53, MAKEFLAGS='j6', 6 cores when building stuff instead of 2
+
+
+$ find . -name "*.asd" -type f -delete          // find all asd files in current tree and delete them
+                                                // -type f: files
+                                                // -type d: directories 
+$ find /var/log -size +10M                      // Find files larger than 10 megabytes.
+
+
+# outputs 3 defined paragraphs from ca.sh
+nl -ba ca.sh | sed -n '130,180p; 560,590p; 600,640p'
+
+du -sh /* 2>/dev/null | sort -rh | head -10     // everything under root
+                                                // 2>/dev/null hides permission errors 
+                                                // sort by bigger size human readable 
+                                                // takes first 10 files 
+
+
+#######################
+###   RETYPE CMDS   ###
+#######################
+
+##  !$ takes the last argument of prev cmd, different from $_ which is a shell variable that works also for scripts
+$ mkdir -p /path/to/folder 
+## cd into folder 
+$ cd !$
+
+## !* reuse all arguments from prev cmd 
+$ chmod 444 file.txt another.py index.html 
+## check them owner 
+$ ls -l !*
+
+## ^old^new fix typo in last cmd 
+$ systemctl start sshf 
+## fix typo 
+$ ^sshf^sshd 
+
+## !number rerun cmd from history, safe for read-only, dangerous for destructive like rm, dd or mkfs 
+$ history
+  499 cmd1 
+  500 cmd2 
+  501 cmd3 
+## rerun cmd1 
+$ !499
+
+## Alt+. takes last arguments, interactive 
+$ tar -czf backup.tar.gz /home/ravi/documents
+## next cmd is ls -lh, we cycle to the last arg with Alt+. 
+$ ls -lh /home/ravi/documents
+
+
+###############################################################################################################################
 
 #####################
 ###     ERRORS    ###
@@ -205,69 +295,3 @@ gpg: keyserver receive failed: No dirmngr
 
 ### create gnupg folder 
 mkdir .local/share/gnupg    
-
-
-###############################################################################################################################
-
-
-$ nohup <SOMEPKG> &                             // start from/indie of terminal
-
-$ xdg-open file.txt					// open file
-$ xdg-mime query filetype file.pdf			// get filetype
-$ xdg-mime query default application/pdf		// ask default pdf app 
-$ xdg-mime default some_app.desktop application/pdf 	// set some_app as default pdf
-                                                    	// if .desktop doesnt exist, create in /usr/share/applications/
-
-$ /bin/ls						// outputs original ls w/o aliases
-$ /bin/ls | entr -s 'firefox localhost:3000'
-
-$ cd -							// into last dir
-
-$ ^r							// search cmd mode
-							// ^R again, search next one
-
-$ history						// show cmds history
-## add to bashrc (have to try on zshrc):
-## HISTTIMEFORMAT="%Y-%m-%d %T "	
-
-$ cmd1 && cmd2                                  // runs cmd2 only after cmd1
-$ cmd1; cmd2                                    // runs cmd2 even if cmd1 fails
-
-$ git commit -m "whatever..." || echo "Commit failed" // conditional execution
-
-$ grep 'string' directory-path/*.*              // find 'string' in all files of
-                                                // directory-path/
-
-
-
-$ pstree                                        // show processes currently running on system
-
-
-$ sudo loadkeys -d                              // change keyboard layout to default
-
-
-
-$ cat error.log | sort | uniq                   // cat to read file 
-                                                // sort it line by line 
-                                                // uniq to eliminate duplicates
-
-$ chown -R xxx: xxx                             // change ownership, after recylcing home dir for instance
-
-echo $(find . -maxdepth 2 -type d) >> ALBUMS
-## edit /etc/makepkg.conf around line 53, MAKEFLAGS='j6', 6 cores when building stuff instead of 2
-
-
-$ find . -name "*.asd" -type f -delete          // find all asd files in current tree and delete them
-                                                // -type f: files
-                                                // -type d: directories 
-$ find /var/log -size +10M                      // Find files larger than 10 megabytes.
-
-
-
-
-
-
-# outputs 3 defined paragraphs from ca.sh
-nl -ba ca.sh | sed -n '130,180p; 560,590p; 600,640p'
-
-
